services:
  php:
    build: ./php-app
    env_file:
      - .env
    volumes:
      - ./php-app/src:/var/www/html
      - ./php-app/src/data:/var/www/html/data
    restart: unless-stopped
    networks:
      - changelog-network

  cloudflare-tunnel:
    depends_on:
      - php
    image: cloudflare/cloudflared:latest
    command: tunnel run --token ${CLOUDFLARE_TUNNEL_TOKEN}
    env_file:
      - .env
    restart: unless-stopped
    networks:
      - changelog-network

networks:
  changelog-network:
    driver: bridge

